<?php

declare(strict_types=1);

namespace jinx\oracle;

final class CoalescedOraclePhpEmitter
{
    /**
     * Emit a standalone executable PHP program from coalesced Oracle ops.
     *
     * @param list<array<string, mixed>> $ops
     */
    public static function emitProgram(array $ops): string
    {
        $lines = [];

        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'declare(strict_types=1);';
        $lines[] = '';
        $lines[] = '// Generated by JINX coalesced Oracle compiler.';
        $lines[] = '// Do not edit by hand.';
        $lines[] = '';

        $needsReadLocal = self::needsReadLocal($ops);

        if ($needsReadLocal) {
            $lines[] = 'function jinx_read_local(array $locals, array $runtimeLocals, string $name): mixed';
            $lines[] = '{';
            $lines[] = '    if (array_key_exists($name, $locals)) {';
            $lines[] = '        return $locals[$name];';
            $lines[] = '    }';
            $lines[] = '';
            $lines[] = '    if (array_key_exists($name, $runtimeLocals)) {';
            $lines[] = '        return $runtimeLocals[$name];';
            $lines[] = '    }';
            $lines[] = '';
            $lines[] = '    throw new RuntimeException("Missing runtime local: {$name}");';
            $lines[] = '}';
            $lines[] = '';
        }

        $lines[] = '$locals = [];';
        $lines[] = '$runtimeLocals = [];';
        $lines[] = '';

        foreach ($ops as $op) {
            switch ($op['op']) {
                case 'OMOV_CONST_LOCAL':
                    $lines[] = '$locals[' . var_export($op['dst'], true) . '] = ' . var_export($op['value'], true) . ';';
                    break;

                case 'OMOV_ADD_LOCAL':
                    $lines[] = '$locals[' . var_export($op['dst'], true) . '] = ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['left'], true) . ') + ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['right'], true) . ');';
                    break;

                case 'OMOV_SUB_LOCAL':
                    $lines[] = '$locals[' . var_export($op['dst'], true) . '] = ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['left'], true) . ') - ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['right'], true) . ');';
                    break;

                case 'OMOV_MUL_LOCAL':
                    $lines[] = '$locals[' . var_export($op['dst'], true) . '] = ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['left'], true) . ') * ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['right'], true) . ');';
                    break;

                case 'ORET_CONST':
                    $lines[] = 'echo ' . var_export((string) $op['value'], true) . ';';
                    $lines[] = 'echo PHP_EOL;';
                    break;

                case 'ORET_ADD_LOCAL':
                    $lines[] = '$jinxResult = jinx_read_local($locals, $runtimeLocals, ' . var_export($op['left'], true) . ') + ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['right'], true) . ');';
                    $lines[] = 'echo (string) $jinxResult;';
                    $lines[] = 'echo PHP_EOL;';
                    break;

                case 'ORET_SUB_LOCAL':
                    $lines[] = '$jinxResult = jinx_read_local($locals, $runtimeLocals, ' . var_export($op['left'], true) . ') - ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['right'], true) . ');';
                    $lines[] = 'echo (string) $jinxResult;';
                    $lines[] = 'echo PHP_EOL;';
                    break;

                case 'ORET_MUL_LOCAL':
                    $lines[] = '$jinxResult = jinx_read_local($locals, $runtimeLocals, ' . var_export($op['left'], true) . ') * ' .
                        'jinx_read_local($locals, $runtimeLocals, ' . var_export($op['right'], true) . ');';
                    $lines[] = 'echo (string) $jinxResult;';
                    $lines[] = 'echo PHP_EOL;';
                    break;

                case 'ORET_BUILTIN_LOCAL':
                    if (($op['builtin'] ?? null) !== 'strlen') {
                        throw new \RuntimeException("Cannot emit builtin: {$op['builtin']}");
                    }

                    $lines[] = '$jinxResult = strlen((string) jinx_read_local($locals, $runtimeLocals, ' . var_export($op['arg'], true) . '));';
                    $lines[] = 'echo (string) $jinxResult;';
                    $lines[] = 'echo PHP_EOL;';
                    break;

                default:
                    throw new \RuntimeException("Cannot emit coalesced Oracle op: {$op['op']}");
            }
        }

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @param list<array<string, mixed>> $ops
     */
    private static function needsReadLocal(array $ops): bool
    {
        foreach ($ops as $op) {
            if (in_array($op['op'], [
                'OMOV_ADD_LOCAL',
                'OMOV_SUB_LOCAL',
                'OMOV_MUL_LOCAL',
                'ORET_ADD_LOCAL',
                'ORET_SUB_LOCAL',
                'ORET_MUL_LOCAL',
                'ORET_BUILTIN_LOCAL',
            ], true)) {
                return true;
            }
        }

        return false;
    }
}
