<?php

declare(strict_types=1);

namespace jinx\server;

require_once __DIR__ . '/PhpToJinxLowerer.php';
require_once __DIR__ . '/CoalescedOracleCompiler.php';

use jinx\lowering\PhpToJinxLowerer;
use jinx\oracle\CoalescedOracleCompiler;

final class JinxCompiledCache
{
    public static function runPhpFile(string $sourcePath, array $runtimeLocals = []): mixed
    {
        $compiledPath = self::compiledPathFor($sourcePath);
        self::compileIfStale($sourcePath, $compiledPath);

        $compiled = require $compiledPath;

        if (!$compiled instanceof \Closure) {
            throw new \RuntimeException("Compiled file did not return a Closure: {$compiledPath}");
        }

        return $compiled($runtimeLocals);
    }

    public static function compileIfStale(string $sourcePath, string $compiledPath): void
    {
        if (!is_file($sourcePath)) {
            throw new \RuntimeException("Missing source file: {$sourcePath}");
        }

        if (
            is_file($compiledPath)
            && filemtime($compiledPath) !== false
            && filemtime($sourcePath) !== false
            && filemtime($compiledPath) >= filemtime($sourcePath)
        ) {
            return;
        }

        $jinx = PhpToJinxLowerer::lowerFile($sourcePath);
        $ops = CoalescedOracleCompiler::compileJinx($jinx);
        $php = self::emitClosureFile($ops, $sourcePath, $jinx);

        $dir = dirname($compiledPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        $tmp = $compiledPath . '.tmp.' . getmypid();
        file_put_contents($tmp, $php);
        rename($tmp, $compiledPath);
    }

    public static function compiledPathFor(string $sourcePath): string
    {
        $root = dirname(__DIR__);
        $hash = sha1(realpath($sourcePath) ?: $sourcePath);

        return $root . '/build/compiled-cache/' . $hash . '.compiled.php';
    }

    /**
     * @param list<array<string, mixed>> $ops
     */
    private static function emitClosureFile(array $ops, string $sourcePath, string $jinx): string
    {
        $lines = [];

        $needsReadLocal = self::needsReadLocal($ops);

        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'declare(strict_types=1);';
        $lines[] = '';
        $lines[] = '// Generated by JINX compiled cache.';
        $lines[] = '// Source: ' . str_replace(["\r", "\n"], '', $sourcePath);
        $lines[] = '// Source sha1: ' . sha1_file($sourcePath);
        $lines[] = '// JINX sha1: ' . sha1($jinx);
        $lines[] = '';
        $lines[] = 'return static function (array $runtimeLocals = []): mixed {';
        $lines[] = '    $locals = [];';

        if ($needsReadLocal) {
            $lines[] = '';
            $lines[] = '    $readLocal = static function (string $name) use (&$locals, &$runtimeLocals): mixed {';
            $lines[] = '        if (array_key_exists($name, $locals)) {';
            $lines[] = '            return $locals[$name];';
            $lines[] = '        }';
            $lines[] = '';
            $lines[] = '        if (array_key_exists($name, $runtimeLocals)) {';
            $lines[] = '            return $runtimeLocals[$name];';
            $lines[] = '        }';
            $lines[] = '';
            $lines[] = '        throw new RuntimeException("Missing runtime local: {$name}");';
            $lines[] = '    };';
        }

        foreach ($ops as $op) {
            switch ($op['op']) {
                case 'OMOV_CONST_LOCAL':
                    $lines[] = '    $locals[' . var_export($op['dst'], true) . '] = ' . var_export($op['value'], true) . ';';
                    break;

                case 'ORET_CONST':
                    $lines[] = '    return ' . var_export($op['value'], true) . ';';
                    break;

                case 'ORET_ADD_LOCAL':
                    $lines[] = '    return $readLocal(' . var_export($op['left'], true) . ') + $readLocal(' . var_export($op['right'], true) . ');';
                    break;

                case 'ORET_SUB_LOCAL':
                    $lines[] = '    return $readLocal(' . var_export($op['left'], true) . ') - $readLocal(' . var_export($op['right'], true) . ');';
                    break;

                case 'ORET_MUL_LOCAL':
                    $lines[] = '    return $readLocal(' . var_export($op['left'], true) . ') * $readLocal(' . var_export($op['right'], true) . ');';
                    break;

                case 'ORET_BUILTIN_LOCAL':
                    if ($op['builtin'] !== 'strlen') {
                        throw new \RuntimeException("Cannot emit builtin: {$op['builtin']}");
                    }

                    $lines[] = '    return strlen((string) $readLocal(' . var_export($op['arg'], true) . '));';
                    break;

                default:
                    throw new \RuntimeException("Cannot emit coalesced Oracle op: {$op['op']}");
            }
        }

        $lines[] = '    return null;';
        $lines[] = '};';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * @param list<array<string, mixed>> $ops
     */
    private static function needsReadLocal(array $ops): bool
    {
        foreach ($ops as $op) {
            if (in_array($op['op'], [
                'ORET_ADD_LOCAL',
                'ORET_SUB_LOCAL',
                'ORET_MUL_LOCAL',
                'ORET_BUILTIN_LOCAL',
            ], true)) {
                return true;
            }
        }

        return false;
    }
}
