<?php

declare(strict_types=1);

namespace jinx\web;

/**
 * Generated Oracle-shaped dispatch table for hot worker-safe PHP builtins.
 *
 * This is the PHP carrier for the same idea as the C Oracle/PASM dispatcher:
 * a validated builtin name enters a compact direct dispatch table instead of
 * the generic worker wrapper metadata path.
 */
final class WebNativeOracleDispatch
{
    /** @var array<string,true>|null */
    private static ?array $names = null;

    public static function has(string $name): bool
    {
        if (self::$names === null) {
            self::$names = array_fill_keys(self::names(), true);
        }

        return isset(self::$names[strtolower($name)]);
    }

    /** @return list<string> */
    public static function names(): array
    {
        return [
            'abs',
            'acos',
            'acosh',
            'addcslashes',
            'addslashes',
            'array_all',
            'array_any',
            'array_change_key_case',
            'array_chunk',
            'array_column',
            'array_combine',
            'array_count_values',
            'array_diff',
            'array_diff_assoc',
            'array_diff_key',
            'array_diff_uassoc',
            'array_diff_ukey',
            'array_fill',
            'array_fill_keys',
            'array_filter',
            'array_find',
            'array_find_key',
            'array_flip',
            'array_intersect',
            'array_intersect_assoc',
            'array_intersect_key',
            'array_intersect_uassoc',
            'array_intersect_ukey',
            'array_is_list',
            'array_key_exists',
            'array_key_first',
            'array_key_last',
            'array_keys',
            'array_map',
            'array_merge',
            'array_merge_recursive',
            'array_pad',
            'array_product',
            'array_rand',
            'array_reduce',
            'array_replace',
            'array_replace_recursive',
            'array_reverse',
            'array_search',
            'array_slice',
            'array_sum',
            'array_udiff',
            'array_udiff_assoc',
            'array_udiff_uassoc',
            'array_uintersect',
            'array_uintersect_assoc',
            'array_uintersect_uassoc',
            'array_values',
            'asin',
            'asinh',
            'assert',
            'atan',
            'atan2',
            'atanh',
            'base64_decode',
            'base64_encode',
            'base_convert',
            'basename',
            'bin2hex',
            'bindec',
            'boolval',
            'cal_days_in_month',
            'cal_from_jd',
            'cal_info',
            'cal_to_jd',
            'call_user_func',
            'call_user_func_array',
            'ceil',
            'checkdate',
            'checkdnsrr',
            'chop',
            'chr',
            'chunk_split',
            'class_exists',
            'class_implements',
            'class_parents',
            'class_uses',
            'connection_aborted',
            'connection_status',
            'constant',
            'convert_uudecode',
            'convert_uuencode',
            'cos',
            'cosh',
            'count',
            'count_chars',
            'crc32',
            'crypt',
            'ctype_alnum',
            'ctype_alpha',
            'ctype_cntrl',
            'ctype_digit',
            'ctype_graph',
            'ctype_lower',
            'ctype_print',
        ];
    }

    /**
     * @param list<mixed> $args
     */
    public static function call(string $name, array $args): mixed
    {
        return self::callLowercase(strtolower($name), $args);
    }

    /**
     * @param list<mixed> $args
     */
    public static function callLowercase(string $name, array $args): mixed
    {
        return match ($name) {
            'abs' => abs(...$args),
            'acos' => acos(...$args),
            'acosh' => acosh(...$args),
            'addcslashes' => addcslashes(...$args),
            'addslashes' => addslashes(...$args),
            'array_all' => array_all(...$args),
            'array_any' => array_any(...$args),
            'array_change_key_case' => array_change_key_case(...$args),
            'array_chunk' => array_chunk(...$args),
            'array_column' => array_column(...$args),
            'array_combine' => array_combine(...$args),
            'array_count_values' => array_count_values(...$args),
            'array_diff' => array_diff(...$args),
            'array_diff_assoc' => array_diff_assoc(...$args),
            'array_diff_key' => array_diff_key(...$args),
            'array_diff_uassoc' => array_diff_uassoc(...$args),
            'array_diff_ukey' => array_diff_ukey(...$args),
            'array_fill' => array_fill(...$args),
            'array_fill_keys' => array_fill_keys(...$args),
            'array_filter' => array_filter(...$args),
            'array_find' => array_find(...$args),
            'array_find_key' => array_find_key(...$args),
            'array_flip' => array_flip(...$args),
            'array_intersect' => array_intersect(...$args),
            'array_intersect_assoc' => array_intersect_assoc(...$args),
            'array_intersect_key' => array_intersect_key(...$args),
            'array_intersect_uassoc' => array_intersect_uassoc(...$args),
            'array_intersect_ukey' => array_intersect_ukey(...$args),
            'array_is_list' => array_is_list(...$args),
            'array_key_exists' => array_key_exists(...$args),
            'array_key_first' => array_key_first(...$args),
            'array_key_last' => array_key_last(...$args),
            'array_keys' => array_keys(...$args),
            'array_map' => array_map(...$args),
            'array_merge' => array_merge(...$args),
            'array_merge_recursive' => array_merge_recursive(...$args),
            'array_pad' => array_pad(...$args),
            'array_product' => array_product(...$args),
            'array_rand' => array_rand(...$args),
            'array_reduce' => array_reduce(...$args),
            'array_replace' => array_replace(...$args),
            'array_replace_recursive' => array_replace_recursive(...$args),
            'array_reverse' => array_reverse(...$args),
            'array_search' => array_search(...$args),
            'array_slice' => array_slice(...$args),
            'array_sum' => array_sum(...$args),
            'array_udiff' => array_udiff(...$args),
            'array_udiff_assoc' => array_udiff_assoc(...$args),
            'array_udiff_uassoc' => array_udiff_uassoc(...$args),
            'array_uintersect' => array_uintersect(...$args),
            'array_uintersect_assoc' => array_uintersect_assoc(...$args),
            'array_uintersect_uassoc' => array_uintersect_uassoc(...$args),
            'array_values' => array_values(...$args),
            'asin' => asin(...$args),
            'asinh' => asinh(...$args),
            'assert' => assert(...$args),
            'atan' => atan(...$args),
            'atan2' => atan2(...$args),
            'atanh' => atanh(...$args),
            'base64_decode' => base64_decode(...$args),
            'base64_encode' => base64_encode(...$args),
            'base_convert' => base_convert(...$args),
            'basename' => basename(...$args),
            'bin2hex' => bin2hex(...$args),
            'bindec' => bindec(...$args),
            'boolval' => boolval(...$args),
            'cal_days_in_month' => cal_days_in_month(...$args),
            'cal_from_jd' => cal_from_jd(...$args),
            'cal_info' => cal_info(...$args),
            'cal_to_jd' => cal_to_jd(...$args),
            'call_user_func' => call_user_func(...$args),
            'call_user_func_array' => call_user_func_array(...$args),
            'ceil' => ceil(...$args),
            'checkdate' => checkdate(...$args),
            'checkdnsrr' => checkdnsrr(...$args),
            'chop' => chop(...$args),
            'chr' => chr(...$args),
            'chunk_split' => chunk_split(...$args),
            'class_exists' => class_exists(...$args),
            'class_implements' => class_implements(...$args),
            'class_parents' => class_parents(...$args),
            'class_uses' => class_uses(...$args),
            'connection_aborted' => connection_aborted(...$args),
            'connection_status' => connection_status(...$args),
            'constant' => constant(...$args),
            'convert_uudecode' => convert_uudecode(...$args),
            'convert_uuencode' => convert_uuencode(...$args),
            'cos' => cos(...$args),
            'cosh' => cosh(...$args),
            'count' => count(...$args),
            'count_chars' => count_chars(...$args),
            'crc32' => crc32(...$args),
            'crypt' => crypt(...$args),
            'ctype_alnum' => ctype_alnum(...$args),
            'ctype_alpha' => ctype_alpha(...$args),
            'ctype_cntrl' => ctype_cntrl(...$args),
            'ctype_digit' => ctype_digit(...$args),
            'ctype_graph' => ctype_graph(...$args),
            'ctype_lower' => ctype_lower(...$args),
            'ctype_print' => ctype_print(...$args),
            default => throw new \RuntimeException("No Oracle dispatch entry for {$name}"),
        };
    }

    /**
     * @param list<mixed> $args
     */
    public static function tryCallLowercase(string $name, array $args, bool &$hit): mixed
    {
        $hit = true;

        return match ($name) {
            'abs' => abs(...$args),
            'acos' => acos(...$args),
            'acosh' => acosh(...$args),
            'addcslashes' => addcslashes(...$args),
            'addslashes' => addslashes(...$args),
            'array_all' => array_all(...$args),
            'array_any' => array_any(...$args),
            'array_change_key_case' => array_change_key_case(...$args),
            'array_chunk' => array_chunk(...$args),
            'array_column' => array_column(...$args),
            'array_combine' => array_combine(...$args),
            'array_count_values' => array_count_values(...$args),
            'array_diff' => array_diff(...$args),
            'array_diff_assoc' => array_diff_assoc(...$args),
            'array_diff_key' => array_diff_key(...$args),
            'array_diff_uassoc' => array_diff_uassoc(...$args),
            'array_diff_ukey' => array_diff_ukey(...$args),
            'array_fill' => array_fill(...$args),
            'array_fill_keys' => array_fill_keys(...$args),
            'array_filter' => array_filter(...$args),
            'array_find' => array_find(...$args),
            'array_find_key' => array_find_key(...$args),
            'array_flip' => array_flip(...$args),
            'array_intersect' => array_intersect(...$args),
            'array_intersect_assoc' => array_intersect_assoc(...$args),
            'array_intersect_key' => array_intersect_key(...$args),
            'array_intersect_uassoc' => array_intersect_uassoc(...$args),
            'array_intersect_ukey' => array_intersect_ukey(...$args),
            'array_is_list' => array_is_list(...$args),
            'array_key_exists' => array_key_exists(...$args),
            'array_key_first' => array_key_first(...$args),
            'array_key_last' => array_key_last(...$args),
            'array_keys' => array_keys(...$args),
            'array_map' => array_map(...$args),
            'array_merge' => array_merge(...$args),
            'array_merge_recursive' => array_merge_recursive(...$args),
            'array_pad' => array_pad(...$args),
            'array_product' => array_product(...$args),
            'array_rand' => array_rand(...$args),
            'array_reduce' => array_reduce(...$args),
            'array_replace' => array_replace(...$args),
            'array_replace_recursive' => array_replace_recursive(...$args),
            'array_reverse' => array_reverse(...$args),
            'array_search' => array_search(...$args),
            'array_slice' => array_slice(...$args),
            'array_sum' => array_sum(...$args),
            'array_udiff' => array_udiff(...$args),
            'array_udiff_assoc' => array_udiff_assoc(...$args),
            'array_udiff_uassoc' => array_udiff_uassoc(...$args),
            'array_uintersect' => array_uintersect(...$args),
            'array_uintersect_assoc' => array_uintersect_assoc(...$args),
            'array_uintersect_uassoc' => array_uintersect_uassoc(...$args),
            'array_values' => array_values(...$args),
            'asin' => asin(...$args),
            'asinh' => asinh(...$args),
            'assert' => assert(...$args),
            'atan' => atan(...$args),
            'atan2' => atan2(...$args),
            'atanh' => atanh(...$args),
            'base64_decode' => base64_decode(...$args),
            'base64_encode' => base64_encode(...$args),
            'base_convert' => base_convert(...$args),
            'basename' => basename(...$args),
            'bin2hex' => bin2hex(...$args),
            'bindec' => bindec(...$args),
            'boolval' => boolval(...$args),
            'cal_days_in_month' => cal_days_in_month(...$args),
            'cal_from_jd' => cal_from_jd(...$args),
            'cal_info' => cal_info(...$args),
            'cal_to_jd' => cal_to_jd(...$args),
            'call_user_func' => call_user_func(...$args),
            'call_user_func_array' => call_user_func_array(...$args),
            'ceil' => ceil(...$args),
            'checkdate' => checkdate(...$args),
            'checkdnsrr' => checkdnsrr(...$args),
            'chop' => chop(...$args),
            'chr' => chr(...$args),
            'chunk_split' => chunk_split(...$args),
            'class_exists' => class_exists(...$args),
            'class_implements' => class_implements(...$args),
            'class_parents' => class_parents(...$args),
            'class_uses' => class_uses(...$args),
            'connection_aborted' => connection_aborted(...$args),
            'connection_status' => connection_status(...$args),
            'constant' => constant(...$args),
            'convert_uudecode' => convert_uudecode(...$args),
            'convert_uuencode' => convert_uuencode(...$args),
            'cos' => cos(...$args),
            'cosh' => cosh(...$args),
            'count' => count(...$args),
            'count_chars' => count_chars(...$args),
            'crc32' => crc32(...$args),
            'crypt' => crypt(...$args),
            'ctype_alnum' => ctype_alnum(...$args),
            'ctype_alpha' => ctype_alpha(...$args),
            'ctype_cntrl' => ctype_cntrl(...$args),
            'ctype_digit' => ctype_digit(...$args),
            'ctype_graph' => ctype_graph(...$args),
            'ctype_lower' => ctype_lower(...$args),
            'ctype_print' => ctype_print(...$args),
            default => self::miss($hit),
        };
    }

    private static function miss(bool &$hit): null
    {
        $hit = false;

        return null;
    }
}
