<?php

declare(strict_types=1);

if ($argc < 3 || $argc > 4) {
    fwrite(STDERR, "Usage: php scripts/generate-oracle-dispatch-table.php oracle_asm_index.json output.c [limit]\n");
    exit(1);
}

$indexPath = $argv[1];
$outputPath = $argv[2];
$limit = isset($argv[3]) ? max(1, (int) $argv[3]) : null;

if (!is_file($indexPath)) {
    fwrite(STDERR, "Missing Oracle ASM index: {$indexPath}\n");
    exit(1);
}

$index = json_decode((string) file_get_contents($indexPath), true);

if (!is_array($index)) {
    fwrite(STDERR, "Invalid Oracle ASM index JSON\n");
    exit(1);
}

$baseDir = dirname($indexPath);
$rows = [];
$headers = [];

foreach (($index['files'] ?? []) as $file) {
    if (!is_array($file)) {
        continue;
    }

    $outputFile = $file['output_file'] ?? null;

    if (!is_string($outputFile) || $outputFile === '') {
        continue;
    }

    $headerPath = $baseDir . '/' . $outputFile;

    if (!is_file($headerPath)) {
        continue;
    }

    $headers[$outputFile] = true;

    $text = (string) file_get_contents($headerPath);

    preg_match_all(
        '/\/\*\s*Callable:\s*([^*]+?)\s*\*\/\s*static\s+inline\s+JinxValue\s+(jinx_ora_[A-Za-z0-9_]+)\s*\(/',
        $text,
        $matches,
        PREG_SET_ORDER
    );

    foreach ($matches as $match) {
        $name = trim($match[1]);
        $wrapper = trim($match[2]);

        if ($name === '' || $wrapper === '') {
            continue;
        }

        $rows[$name] = [
            'name' => $name,
            'wrapper' => $wrapper,
        ];

        if ($limit !== null && count($rows) >= $limit) {
            break 2;
        }
    }
}

if ($rows === []) {
    fwrite(STDERR, "No wrappers found in generated Oracle ASM headers\n");
    exit(1);
}

$outDir = dirname($outputPath);
if (!is_dir($outDir)) {
    mkdir($outDir, 0777, true);
}

$code = [];
$code[] = '/* Generated by scripts/generate-oracle-dispatch-table.php. Do not edit by hand. */';
$code[] = '#include "jinx_builtin_dispatch.h"';
$code[] = '';

foreach (array_keys($headers) as $header) {
    $code[] = '#include "../build/oracle-asm/' . c_escape($header) . '"';
}

$code[] = '';
$code[] = '#include <string.h>';
$code[] = '';
$code[] = 'static const JinxOracleDispatchEntry oracle_dispatch_table[] = {';

foreach ($rows as $row) {
    $code[] = sprintf(
        '    { "%s", %s },',
        c_escape($row['name']),
        $row['wrapper']
    );
}

$code[] = '    { NULL, NULL }';
$code[] = '};';
$code[] = '';
$code[] = 'JinxOracleWrapper jinx_lookup_oracle_wrapper(const char *name) {';
$code[] = '    for (size_t i = 0; oracle_dispatch_table[i].name != NULL; i++) {';
$code[] = '        if (strcmp(oracle_dispatch_table[i].name, name) == 0) {';
$code[] = '            return oracle_dispatch_table[i].wrapper;';
$code[] = '        }';
$code[] = '    }';
$code[] = '';
$code[] = '    return NULL;';
$code[] = '}';
$code[] = '';
$code[] = 'JinxValue jinx_call_builtin_through_oracle(';
$code[] = '    const char *name,';
$code[] = '    const JinxValue *args,';
$code[] = '    size_t argc';
$code[] = ') {';
$code[] = '    JinxOracleWrapper wrapper = jinx_lookup_oracle_wrapper(name);';
$code[] = '';
$code[] = '    if (wrapper == NULL) {';
$code[] = '        return jinx_value_null();';
$code[] = '    }';
$code[] = '';
$code[] = '    JinxOracleAsmContext ctx;';
$code[] = '    jinx_ora_context_init(&ctx, args, argc);';
$code[] = '';
$code[] = '    JinxValue result = wrapper(&ctx);';
$code[] = '';
$code[] = '    if (ctx.error) {';
$code[] = '        return jinx_value_null();';
$code[] = '    }';
$code[] = '';
$code[] = '    return result;';
$code[] = '}';
$code[] = '';

file_put_contents($outputPath, implode(PHP_EOL, $code));

printf(
    "PASS: generated Oracle dispatch table with %d wrappers at %s\n",
    count($rows),
    $outputPath
);

function c_escape(string $value): string
{
    return addcslashes($value, "\\\"\n\r\t");
}
