<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$manifestPath = $argv[1] ?? ($root . '/spec/php-functions.from-runtime.json');
$outPath = $argv[2] ?? ($root . '/runtime/jinx_function_list.generated.h');

$manifest = json_decode((string) file_get_contents($manifestPath), true, 512, JSON_THROW_ON_ERROR);
$functions = $manifest['functions'] ?? [];

if (!is_array($functions) || $functions === []) {
    fwrite(STDERR, "No functions found in {$manifestPath}\n");
    exit(1);
}

usort(
    $functions,
    static fn (array $a, array $b): int => strcmp((string) $a['name'], (string) $b['name'])
);

$names = array_map(
    static fn (array $function): string => (string) $function['name'],
    $functions
);

$lines = [];
$lines[] = '/* Generated by scripts/generate-native-function-list.php. Do not edit by hand. */';
$lines[] = '#ifndef JINX_FUNCTION_LIST_GENERATED_H';
$lines[] = '#define JINX_FUNCTION_LIST_GENERATED_H';
$lines[] = '';
$lines[] = '#include <stddef.h>';
$lines[] = '';
$lines[] = 'static const char *const jinx_all_function_names[] = {';

foreach ($names as $name) {
    $escaped = addcslashes($name, "\\\"");
    $lines[] = '    "' . $escaped . '",';
}

$lines[] = '};';
$lines[] = '';
$lines[] = 'static const size_t jinx_all_function_count = ' . count($names) . 'u;';
$lines[] = '';
$lines[] = '#endif';
$lines[] = '';

file_put_contents($outPath, implode("\n", $lines));

echo "Generated {$outPath} with " . count($names) . " names\n";
